name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        # pulls all commits (needed for lerna / semantic release to correctly version)
         fetch-depth: "0"
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      # fyi https://github.com/lerna/lerna/issues/2542
      - name: Fetch tags
       # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn release:publish --yes --registry=https://registry.npmjs.org
        env:
          NPM_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
